
import { useGLTF } from '@react-three/drei'

const IsleDelfino = (props) => {
    const { nodes, materials } = useGLTF('/models-3d/acidficationModels/isle_delfino.glb')
    return (
      <group {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 2.7]}>
            <group name="Collada_visual_scene_group">
              <group name="SEA">
                <mesh
                  name="SEA_sea01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEA_sea01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="ILE">
                <mesh
                  name="ILE_cliff04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff04-material'].geometry}
                  material={materials.RIC_cliff01}
                />
                <mesh
                  name="ILE_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_slab01-material'].geometry}
                  material={materials.ILE_slab01}
                />
                <mesh
                  name="ILE_corona01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_corona01-material'].geometry}
                  material={materials.ILE_corona01}
                />
                <mesh
                  name="ILE_cliff07-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff07-material'].geometry}
                  material={materials.ILE_cliff07}
                />
                <mesh
                  name="ILE_grass02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_grass02-material'].geometry}
                  material={materials.ILE_grass02}
                />
                <mesh
                  name="ILE_cliff06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff06-material'].geometry}
                  material={materials.ILE_cliff06}
                />
                <mesh
                  name="ILE_cliff05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff05-material'].geometry}
                  material={materials.GEL_cliff01}
                />
                <mesh
                  name="ILE_cliff03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff03-material'].geometry}
                  material={materials.ILE_cliff03}
                />
                <mesh
                  name="ILE_grass03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_grass03-material'].geometry}
                  material={materials.ILE_grass03}
                />
                <mesh
                  name="ILE_cliff08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff08-material'].geometry}
                  material={materials.NOK_cliff01}
                />
                <mesh
                  name="ILE_cliff09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff09-material'].geometry}
                  material={materials.ILE_cliff09}
                />
                <mesh
                  name="ILE_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff01-material'].geometry}
                  material={materials.NOK_cliff03}
                />
                <mesh
                  name="ILE_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_cliff02-material'].geometry}
                  material={materials.NOK_cliff02}
                />
                <mesh
                  name="ILE_lava01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_lava01-material'].geometry}
                  material={materials.COR_stone02}
                />
                <mesh
                  name="ILE_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_stone02-material'].geometry}
                  material={materials.ILE_stone02}
                />
                <mesh
                  name="ILE_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_grass01-material'].geometry}
                  material={materials.ILE_grass01}
                />
                <mesh
                  name="ILE_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['ILE_sand01-material'].geometry}
                  material={materials.ILE_sand01}
                />
              </group>
              <group name="NOK">
                <mesh
                  name="NOK_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="NOK_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_sand01-material'].geometry}
                  material={materials.DSM_sand01}
                />
                <mesh
                  name="NOK_cliff03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_cliff03-material'].geometry}
                  material={materials.NOK_cliff03}
                />
                <mesh
                  name="NOK_ruins01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_ruins01-material'].geometry}
                  material={materials.NOK_ruins01}
                />
                <mesh
                  name="NOK_water01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_water01-material'].geometry}
                  material={materials.NOK_water01}
                />
                <mesh
                  name="NOK_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_stone01-material'].geometry}
                  material={materials.NOK_stone01}
                />
                <mesh
                  name="NOK_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_cliff01-material'].geometry}
                  material={materials.NOK_cliff01}
                />
                <mesh
                  name="NOK_slab02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_slab02-material'].geometry}
                  material={materials.NOK_slab02}
                />
                <mesh
                  name="NOK_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_cliff02-material'].geometry}
                  material={materials.NOK_cliff02}
                />
                <mesh
                  name="NOK_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_grass01-material'].geometry}
                  material={materials.ILE_grass01}
                />
                <mesh
                  name="NOK_house02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_house02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="NOK_ruins02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_ruins02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="NOK_grass02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['NOK_grass02-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="RIC">
                <mesh
                  name="RIC_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="RIC_slab03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_slab03-material'].geometry}
                  material={materials.RIC_slab03}
                />
                <mesh
                  name="RIC_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_slab01-material'].geometry}
                  material={materials.RIC_slab01}
                />
                <mesh
                  name="RIC_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_stone02-material'].geometry}
                  material={materials.RIC_stone02}
                />
                <mesh
                  name="RIC_metal04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_metal04-material'].geometry}
                  material={materials.RIC_metal04}
                />
                <mesh
                  name="RIC_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_cliff01-material'].geometry}
                  material={materials.RIC_cliff01}
                />
                <mesh
                  name="RIC_metal03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_metal03-material'].geometry}
                  material={materials.RIC_metal03}
                />
                <mesh
                  name="RIC_metal05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_metal05-material'].geometry}
                  material={materials.RIC_metal05}
                />
                <mesh
                  name="RIC_stone03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_stone03-material'].geometry}
                  material={materials.RIC_stone03}
                />
                <mesh
                  name="RIC_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_sand01-material'].geometry}
                  material={materials.ILE_sand01}
                />
                <mesh
                  name="RIC_water02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_water02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="RIC_metal01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_metal01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="RIC_metal06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['RIC_metal06-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="PIA">
                <mesh
                  name="PIA_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_grass01-material'].geometry}
                  material={materials.PIA_grass01}
                />
                <mesh
                  name="PIA_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_cliff02-material'].geometry}
                  material={materials.PIA_cliff02}
                />
                <mesh
                  name="PIA_wood10-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood10-material'].geometry}
                  material={materials.PIA_wood10}
                />
                <mesh
                  name="PIA_wood09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood09-material'].geometry}
                  material={materials.PIA_wood09}
                />
                <mesh
                  name="PIA_wood05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood05-material'].geometry}
                  material={materials.PIA_wood05}
                />
                <mesh
                  name="PIA_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood01-material'].geometry}
                  material={materials.PIA_wood01}
                />
                <mesh
                  name="PIA_wood03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood03-material'].geometry}
                  material={materials.PIA_wood03}
                />
                <mesh
                  name="PIA_grass03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_grass03-material'].geometry}
                  material={materials.PIA_grass03}
                />
                <mesh
                  name="PIA_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_cliff01-material'].geometry}
                  material={materials.PIA_cliff01}
                />
                <mesh
                  name="PIA_wood12-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_wood12-material'].geometry}
                  material={materials.PIA_wood12}
                />
                <mesh
                  name="PIA_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIA_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="PIN2">
                <mesh
                  name="PIN2_metal02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_metal02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PIN2_slab02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_slab02-material'].geometry}
                  material={materials.PIN_dalle14}
                />
                <mesh
                  name="PIN2_metal01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_metal01-material'].geometry}
                  material={materials.PIN2_metal01}
                />
                <mesh
                  name="PIN2_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_stone01-material'].geometry}
                  material={materials.PIN2_stone01}
                />
                <mesh
                  name="PIN2_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_cliff01-material'].geometry}
                  material={materials.PIN2_cliff01}
                />
                <mesh
                  name="PIN2_slab09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_slab09-material'].geometry}
                  material={materials.PIN2_slab09}
                />
                <mesh
                  name="PIN2_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_wood01-material'].geometry}
                  material={materials.PIN2_wood01}
                />
                <mesh
                  name="PIN2_slab07-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_slab07-material'].geometry}
                  material={materials.PIN2_slab07}
                />
                <mesh
                  name="PIN2_slab06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_slab06-material'].geometry}
                  material={materials.PIN2_slab06}
                />
                <mesh
                  name="PIN2_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_sand01-material'].geometry}
                  material={materials.PIN2_sand01}
                />
                <mesh
                  name="PIN2_slab05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_slab05-material'].geometry}
                  material={materials.PIN2_slab05}
                />
                <mesh
                  name="PIN2_grass02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN2_grass02-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="AIR">
                <mesh
                  name="AIR_void01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_void01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="AIR_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_slab01-material'].geometry}
                  material={materials.AIR_slab01}
                />
                <mesh
                  name="AIR_sign01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_sign01-material'].geometry}
                  material={materials.AIR_sign01}
                />
                <mesh
                  name="AIR_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_sand01-material'].geometry}
                  material={materials.ILE_sand01}
                />
                <mesh
                  name="AIR_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_stone01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="AIR_plane01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_plane01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="AIR_sky01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_sky01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="AIR_house01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_house01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="AIR_house03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['AIR_house03-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="COR">
                <mesh
                  name="COR_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['COR_stone02-material'].geometry}
                  material={materials.COR_stone02}
                />
                <mesh
                  name="COR_lava01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['COR_lava01-material'].geometry}
                  material={materials.COR_lava01}
                />
                <mesh
                  name="COR_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['COR_stone01-material'].geometry}
                  material={materials.RIC_stone03}
                />
                <mesh
                  name="COR_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['COR_slab01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="DSM">
                <mesh
                  name="DSM_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DSM_slab01-material'].geometry}
                  material={materials.NOK_slab02}
                />
                <mesh
                  name="DSM_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DSM_cliff01-material'].geometry}
                  material={materials.NOK_cliff02}
                />
                <mesh
                  name="DSM_ruins01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DSM_ruins01-material'].geometry}
                  material={materials.NOK_ruins01}
                />
                <mesh
                  name="DSM_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DSM_sand01-material'].geometry}
                  material={materials.DSM_sand01}
                />
              </group>
              <group name="SEW">
                <mesh
                  name="SEW_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_slab01-material'].geometry}
                  material={materials.SEW_slab01}
                />
                <mesh
                  name="SEW_water02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_water02-material'].geometry}
                  material={materials.SEW_water02}
                />
                <mesh
                  name="SEW_water01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_water01-material'].geometry}
                  material={materials.SEW_water01}
                />
                <mesh
                  name="SEW_slab03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_slab03-material'].geometry}
                  material={materials.SEW_slab03}
                />
                <mesh
                  name="SEW_metal01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_metal01-material'].geometry}
                  material={materials.SEW_metal01}
                />
                <mesh
                  name="SEW_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_stone01-material'].geometry}
                  material={materials.SEW_stone01}
                />
                <mesh
                  name="SEW_slab02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_slab02-material'].geometry}
                  material={materials.ILE_slab01}
                />
                <mesh
                  name="SEW_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_sand01-material'].geometry}
                  material={materials.ILE_sand01}
                />
                <mesh
                  name="SEW_sign01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SEW_sign01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="BOO">
                <mesh
                  name="BOO_casino02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_casino02-material'].geometry}
                  material={materials.BOO_casino02}
                />
                <mesh
                  name="BOO_stone03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_stone03-material'].geometry}
                  material={materials.CAS_casino08}
                />
                <mesh
                  name="BOO_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_stone02-material'].geometry}
                  material={materials.BOO_stone02}
                />
                <mesh
                  name="BOO_gold01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_gold01-material'].geometry}
                  material={materials.HOT_gold01}
                />
                <mesh
                  name="BOO_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_stone01-material'].geometry}
                  material={materials.CAS_stone03}
                />
                <mesh
                  name="BOO_casino01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOO_casino01-material'].geometry}
                  material={materials.CAS_slab09}
                />
              </group>
              <group name="HOT">
                <mesh
                  name="HOT_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_stone02-material'].geometry}
                  material={materials.CAS_stone01}
                />
                <mesh
                  name="HOT_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_slab01-material'].geometry}
                  material={materials.CAS_slab03}
                />
                <mesh
                  name="HOT_stone03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_stone03-material'].geometry}
                  material={materials.CAS_stone07}
                />
                <mesh
                  name="HOT_house03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_house03-material'].geometry}
                  material={materials.HOT_house03}
                />
                <mesh
                  name="HOT_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_wood01-material'].geometry}
                  material={materials.HOT_wood01}
                />
                <mesh
                  name="HOT_house04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_house04-material'].geometry}
                  material={materials.HOT_house04}
                />
                <mesh
                  name="HOT_gold01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_gold01-material'].geometry}
                  material={materials.HOT_gold01}
                />
                <mesh
                  name="HOT_slab04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_slab04-material'].geometry}
                  material={materials.HOT_slab04}
                />
                <mesh
                  name="HOT_stone05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_stone05-material'].geometry}
                  material={materials.HOT_stone05}
                />
                <mesh
                  name="HOT_stone04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_stone04-material'].geometry}
                  material={materials.RIC_stone02}
                />
                <mesh
                  name="HOT_water01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_water01-material'].geometry}
                  material={materials.NOK_water01}
                />
                <mesh
                  name="HOT_glass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_glass01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="HOT_house08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_house08-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="HOT_house02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_house02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="HOT_slab05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_slab05-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="HOT_house01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_house01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="HOT_stone09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['HOT_stone09-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="CAS">
                <mesh
                  name="CAS_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_stone01-material'].geometry}
                  material={materials.CAS_stone01}
                />
                <mesh
                  name="CAS_stone03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_stone03-material'].geometry}
                  material={materials.CAS_stone03}
                />
                <mesh
                  name="CAS_slab03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_slab03-material'].geometry}
                  material={materials.CAS_slab03}
                />
                <mesh
                  name="CAS_casino10-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_casino10-material'].geometry}
                  material={materials.CAS_casino10}
                />
                <mesh
                  name="CAS_stone07-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_stone07-material'].geometry}
                  material={materials.CAS_stone07}
                />
                <mesh
                  name="CAS_casino08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_casino08-material'].geometry}
                  material={materials.CAS_casino08}
                />
                <mesh
                  name="CAS_slab09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_slab09-material'].geometry}
                  material={materials.CAS_slab09}
                />
                <mesh
                  name="CAS_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_wood01-material'].geometry}
                  material={materials.HOT_wood01}
                />
                <mesh
                  name="CAS_house01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_house01-material'].geometry}
                  material={materials.HOT_house04}
                />
                <mesh
                  name="CAS_gold01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_gold01-material'].geometry}
                  material={materials.HOT_gold01}
                />
                <mesh
                  name="CAS_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_slab01-material'].geometry}
                  material={materials.HOT_slab04}
                />
                <mesh
                  name="CAS_stone04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_stone04-material'].geometry}
                  material={materials.BOO_stone02}
                />
                <mesh
                  name="CAS_void01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_void01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="CAS_casino09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_casino09-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="CAS_casino05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_casino05-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="CAS_slab08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['CAS_slab08-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="PIR">
                <mesh
                  name="PIR_light01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIR_light01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PIR_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIR_slab01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="DOL">
                <mesh
                  name="DOL_slab05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_slab05-material'].geometry}
                  material={materials.DOL_slab05}
                />
                <mesh
                  name="DOL_house04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house04-material'].geometry}
                  material={materials.DOL_house04}
                />
                <mesh
                  name="DOL_house01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house01-material'].geometry}
                  material={materials.DOL_house01}
                />
                <mesh
                  name="DOL_house03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house03-material'].geometry}
                  material={materials.DOL_house03}
                />
                <mesh
                  name="DOL_slab03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_slab03-material'].geometry}
                  material={materials.DOL_slab03}
                />
                <mesh
                  name="DOL_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_cliff02-material'].geometry}
                  material={materials.DOL_cliff02}
                />
                <mesh
                  name="DOL_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_sand01-material'].geometry}
                  material={materials.DOL_sand01}
                />
                <mesh
                  name="DOL_sign01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_sign01-material'].geometry}
                  material={materials.AIR_sign01}
                />
                <mesh
                  name="DOL_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_stone01-material'].geometry}
                  material={materials.ILE_stone02}
                />
                <mesh
                  name="DOL_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_cliff01-material'].geometry}
                  material={materials.ILE_cliff07}
                />
                <mesh
                  name="DOL_shadow03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_shadow03-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_object01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_object01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_corona01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_corona01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_house05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house05-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_shadow02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_shadow02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_house02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_house08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house08-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOL_house06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOL_house06-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="DOLX2_shine01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['DOLX2_shine01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="PIN">
                <mesh
                  name="PIN_rail01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_rail01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PIN_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_sand01-material'].geometry}
                  material={materials.PIN_sand01}
                />
                <mesh
                  name="PIN_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_stone01-material'].geometry}
                  material={materials.PIN_stone01}
                />
                <mesh
                  name="PIN_dalle15-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle15-material'].geometry}
                  material={materials.PIN_dalle15}
                />
                <mesh
                  name="PIN_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_grass01-material'].geometry}
                  material={materials.PIN_grass01}
                />
                <mesh
                  name="PIN_dalle14-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle14-material'].geometry}
                  material={materials.PIN_dalle14}
                />
                <mesh
                  name="PIN_metal02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_metal02-material'].geometry}
                  material={materials.PIN2_metal01}
                />
                <mesh
                  name="PIN_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_stone02-material'].geometry}
                  material={materials.PIN2_stone01}
                />
                <mesh
                  name="PIN_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_cliff02-material'].geometry}
                  material={materials.PIN2_cliff01}
                />
                <mesh
                  name="PIN_dalle08-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle08-material'].geometry}
                  material={materials.PIN2_slab09}
                />
                <mesh
                  name="PIN_dalle03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle03-material'].geometry}
                  material={materials.PIN2_slab07}
                />
                <mesh
                  name="PIN_dalle04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle04-material'].geometry}
                  material={materials.PIN2_slab06}
                />
                <mesh
                  name="PIN_dalle05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_dalle05-material'].geometry}
                  material={materials.PIN2_slab05}
                />
                <mesh
                  name="PINX1_metal04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX1_metal04-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PIN_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX1_metal07-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX1_metal07-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX1_metal10-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX1_metal10-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX1_metal06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX1_metal06-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX4_metal02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX4_metal02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX2_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX2_wood01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PINX3_metal01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PINX3_metal01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="PIN_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['PIN_wood01-material'].geometry}
                  material={materials.Merged_materials}
                />
              </group>
              <group name="SIR">
                <mesh
                  name="SIR_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_grass01-material'].geometry}
                  material={materials.SIR_grass01}
                />
                <mesh
                  name="SIR_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_sand01-material'].geometry}
                  material={materials.SIR_sand01}
                />
                <mesh
                  name="SIR_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_cliff01-material'].geometry}
                  material={materials.ILE_cliff03}
                />
                <mesh
                  name="SIR_shadow01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_shadow01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="SIR_dalle01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_dalle01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="SIR_grass02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_grass02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="SIR_wood01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_wood01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="SIR_wood03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_wood03-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="SIR_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_stone01-material'].geometry}
                  material={materials.SIR_stone01}
                />
                <mesh
                  name="SIR_wood02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIR_wood02-material'].geometry}
                  material={materials.PIN2_wood01}
                />
                <mesh
                  name="SIRX1_wood03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['SIRX1_wood03-material'].geometry}
                  material={materials.PIN2_wood01}
                />
              </group>
              <group name="GEL">
                <mesh
                  name="GELX1_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GELX1_stone01-material'].geometry}
                  material={materials.GELX1_stone01}
                />
                <mesh
                  name="GEL_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_cliff01-material'].geometry}
                  material={materials.GEL_cliff01}
                />
                <mesh
                  name="GEL_sand01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_sand01-material'].geometry}
                  material={materials.GEL_sand01}
                />
                <mesh
                  name="GEL_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_grass01-material'].geometry}
                  material={materials.ILE_grass02}
                />
                <mesh
                  name="GEL_cliff02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_cliff02-material'].geometry}
                  material={materials.ILE_cliff06}
                />
                <mesh
                  name="GEL_glass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_glass01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_wood07-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood07-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GELX1_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GELX1_stone02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_wood05-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood05-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_house01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_house01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_wood03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood03-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_wood11-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood11-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_wood09-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood09-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GEL_slab01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_slab01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="GELX3_metal01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GELX3_metal01-material'].geometry}
                  material={materials.GELX4_metal01}
                />
                <mesh
                  name="GEL_slab02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_slab02-material'].geometry}
                  material={materials.GELX2_slab01}
                />
                <mesh
                  name="GEL_wood06-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['GEL_wood06-material'].geometry}
                  material={materials.GEL_wood06}
                />
              </group>
              <group name="BIA">
                <mesh
                  name="BIA_water02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_water02-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="BIA_grass03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_grass03-material'].geometry}
                  material={materials.BIA_grass03}
                />
                <mesh
                  name="BIA_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_stone02-material'].geometry}
                  material={materials.BIA_stone02}
                />
                <mesh
                  name="BIA_grass01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_grass01-material'].geometry}
                  material={materials.ILE_grass03}
                />
                <mesh
                  name="BIA_cliff01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_cliff01-material'].geometry}
                  material={materials.ILE_cliff09}
                />
                <mesh
                  name="BIA_water01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_water01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="BIA_house04-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_house04-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="BIA_house03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIA_house03-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="BIAX1_House1-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIAX1_House1-material'].geometry}
                  material={materials.BIA_house01}
                />
                <mesh
                  name="BIAX4_object01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIAX4_object01-material'].geometry}
                  material={materials.BIAX2_object01}
                />
                <mesh
                  name="BIAX2_object01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BIAX2_object01-material'].geometry}
                  material={materials.BIAX2_object01}
                />
              </group>
              <group name="BOW">
                <mesh
                  name="BOWX1_sign01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOWX1_sign01-material'].geometry}
                  material={materials.Merged_materials}
                />
                <mesh
                  name="BOWX1_stone03-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOWX1_stone03-material'].geometry}
                  material={materials.BOWX1_stone03}
                />
                <mesh
                  name="BOWX1_stone02-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOWX1_stone02-material'].geometry}
                  material={materials.BOW_stone3}
                />
                <mesh
                  name="BOWX1_stone01-material"
                  castShadow
                  receiveShadow
                  geometry={nodes['BOWX1_stone01-material'].geometry}
                  material={materials.BOWX1_stone01}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    )
  };

export default IsleDelfino;
useGLTF.preload('/models-3d/acidficationModels/isle_delfino.glb')